<?php

namespace Cashware\Bootswatcher;

use Psr\SimpleCache\CacheInterface;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\ORM\DataExtension;

/**
 * Class \Cashware\Bootswatcher\MemberExtension
 *
 * @property Member|MemberExtension $owner
 * @property string $Theme
 */
class MemberExtension extends DataExtension
{

    private static $db = [
        'Theme' => 'Enum("auto,default,cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,morph,pulse,quartz,sandstone,simplex,sketchy,slate,solar,spacelab,superhero,united,vapor,yeti,zephyr","auto")'
    ];

    public function onBeforeWrite()
    {
        parent::onBeforeWrite(); // TODO: Change the autogenerated stub
    }
}