<?php

namespace Firesphere\JobHunt\Extensions;

use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Assets\File;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\FileField;
use SilverStripe\ORM\DataExtension;

/**
 * Class \Firesphere\JobHunt\Extensions\SiteConfigExtension
 *
 * @property SiteConfig|SiteConfigExtension $owner
 * @property int $DemoCSVID
 * @method File DemoCSV()
 */
class SiteConfigExtension extends DataExtension
{
    private static $has_one = [
        'DemoCSV' => File::class
    ];

    private static $owns = [
        'DemoCSV'
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldToTab('Root.Main', UploadField::create('DemoCSV', 'Demo CSV'));
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }
}
