<?php

namespace Firesphere\JobHunt\Controllers;

use Firesphere\JobHunt\Pages\ApplicationPage;
use SilverStripe\View\Requirements;

/**
 * Class \Firesphere\JobHunt\Controllers\ApplicationPageController
 *
 * @property ApplicationPage $dataRecord
 * @method ApplicationPage data()
 * @mixin ApplicationPage
 */
class ApplicationPageController extends \PageController
{
    private static $allowed_actions = [
        'application'
    ];

    public function init()
    {
        Requirements::javascript('silverstripe/admin:client/dist/tinymce/tinymce.min.js');
        Requirements::css('silverstripe/admin:client/dist/styles/editor.css');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function application()
    {
        $params = $this->getURLParams();
        $this->Application = $params['ID'];
    }

}
