<?php

namespace Firesphere\JobHunt\Controllers;

use Firesphere\JobHunt\Pages\ApplicationPage;
use SilverStripe\Security\Security;

/**
 * Class \Firesphere\JobHunt\Controllers\HomePageController
 *
 */
class HomePageController extends \PageController
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Security::getCurrentUser() && !$this->getRequest()->getVar('cmspreview')) {
            return $this->redirect(ApplicationPage::get()->first()->Link());
        }
    }
}
