import body from './src/body';
import forms from './src/forms';
import moods from './src/moods';
import profile from './src/profile';
import calendar from './src/calendar';
body();
forms();
moods();
profile();
// calendar();
